app:
  port: 8082


database:
  host: localhost
  port: 5435
  user: postgres
  password: 1234
  name: order

redis:
  host: 127.0.0.1
  port: 6379
  password:



secret:
  jwt_secret: "5ecre7"

product:
  host: http://localhost:8081

